namespace WillovateSmartSlot.Api.DTOs;

public sealed record AmbientAssetDto(
    string Url,
    string Name,
    string Type,
    long Size,
    DateTime UploadedAt);

public sealed record OfferDto(
    Guid Id,
    Guid BusinessId,
    string Title,
    string Description,
    string Category,
    decimal OriginalPrice,
    decimal OfferPrice,
    int DiscountPercentage,
    DateOnly StartDate,
    DateOnly EndDate,
    string StartTime,
    string EndTime,
    int TotalCapacity,
    int MaxBookingPerCustomer,
    string TermsAndConditions,
    string Status,
    string? ImageUrl,
    string? ThumbnailUrl,
    AmbientAssetDto? AmbientAsset,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    int Popularity,
    int SlotCount,
    int BookedSeats,
    int RemainingSeats);

public sealed record OfferCreateDto(
    Guid BusinessId,
    string Title,
    string Description,
    string Category,
    decimal OriginalPrice,
    decimal OfferPrice,
    DateOnly StartDate,
    DateOnly EndDate,
    string? StartTime,
    string? EndTime,
    int TotalCapacity,
    int MaxBookingPerCustomer,
    string? TermsAndConditions,
    string Status,
    string? ImageUrl,
    string? ThumbnailUrl,
    AmbientAssetDto? AmbientAsset,
    int? Popularity);

public sealed record OfferUpdateDto(
    string Title,
    string Description,
    string Category,
    decimal OriginalPrice,
    decimal OfferPrice,
    DateOnly StartDate,
    DateOnly EndDate,
    string? StartTime,
    string? EndTime,
    int TotalCapacity,
    int MaxBookingPerCustomer,
    string? TermsAndConditions,
    string Status,
    string? ImageUrl,
    string? ThumbnailUrl,
    AmbientAssetDto? AmbientAsset,
    int? Popularity);
